### PR TITLE
Feature/resources with custom domain

### PR DESCRIPTION
**Pull request by joelvh**
* Uses `nanoid` w/ `nanoid-good` to generate short paths and remove "bad" words
* Make UI customizable
* Add `?vanity=` to specify a vanity URL name
* Uses environment variables for multiple environments rather than `config.json`
* Creates CloudFront distribution for SSL and custom domain
* Adds Serverless Framework plugins to manage custom domains and S3 deployments
* Minor refactorings

### CODE REVIEW

**Comment by danielireson** [comment]
Awesome stuff Joel, thanks for making these improvements.

**Comment by joelvh** [comment]
No problem @danielireson - glad you got the groundwork laid down.

Are you at all intending to keep building on this or was this a one-time project?

For instance, adding analytics would be a good feature leveraging S3 logs or other means.

**Comment by danielireson** [comment]
This was originally created for a tutorial a couple of years ago on my blog and I haven't made any considerable improvements to the codebase since then. As it stands I probably won't be making more updates.

**Comment by joelvh** [comment]
OK, thanks @danielireson. Great work on this.

**Comment by joelvh** [comment]
hey @danielireson would you be interested in transferring ownership of the project so I can build in analytics and other features?

**Pull request merged**
